/* mbed Microcontroller Library
 * Copyright (c) 2018 GigaDevice Semiconductor Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include "PeripheralPins.h"
//#include "gd32xxyy_gpio.h"


/* Generated remapping names */
const int GD_GPIO_REMAP[] = {
  0x00000000,
#if __has_include("gd32f10x_remap.h")
#define __REMAP_NAME__(remap) GPIO_ ## remap,
#include "gd32f30x_remap.h"
#undef __REMAP_NAME__
#endif
};

enum GD_GPIO_REMAP_NAME {
  REMAP_NONE = 0U,
#if __has_include("gd32f30x_remap.h")
#define __REMAP_NAME__(remap) remap,
#include "gd32f30x_remap.h"
#undef __REMAP_NAME__
#define __REMAP_NAME__(remap) DISABLE_ ## remap = GPIO_ ## remap | (1U << 6),
#include "gd32f30x_remap.h"
#undef __REMAP_NAME__
#endif
};

/* GPIO MODE */
const int GD_GPIO_MODE[] = {
  GPIO_MODE_AIN,					/* 0 */
  GPIO_MODE_IN_FLOATING,	/* 1 */
  GPIO_MODE_IPD,					/* 2 */
  GPIO_MODE_IPU,					/* 3 */
  GPIO_MODE_OUT_OD,				/* 4 */
  GPIO_MODE_OUT_PP,				/* 5 */
  GPIO_MODE_AF_OD,				/* 6 */
  GPIO_MODE_AF_PP,				/* 7 */
};

/* GPIO SPEED */
const int GD_GPIO_SPEED[] = {
	GPIO_OSPEED_10MHZ,	/* 0 */
	GPIO_OSPEED_2MHZ,		/* 1 */
	GPIO_OSPEED_50MHZ,	/* 2 */
	GPIO_OSPEED_MAX,		/* 3 */
};

/* =====
 * Note: Commented lines are alternative possibilities which are not used per default.
 *       If you change them, you will have to know what you are doing
 * =====
 */

/* ADC PinMap */
const PinMap PinMap_ADC[] = {
  {PORTA_0,					ADC0, GD_PIN_FUNC_ANALOG_CH(0)}, /* ADC0_IN0 */
  //{PORTA_0_ALT1,  ADC1, GD_PIN_FUNC_ANALOG_CH(0)}, /* ADC1_IN0 */
  //{PORTA_0_ALT2,  ADC2, GD_PIN_FUNC_ANALOG_CH(0)}, /* ADC2_IN0 */
  {PORTA_1,					ADC0, GD_PIN_FUNC_ANALOG_CH(1)}, /* ADC0_IN1 */
  //{PORTA_1_ALT1,  ADC1, GD_PIN_FUNC_ANALOG_CH(1)}, /* ADC1_IN1 */
  //{PORTA_1_ALT2,  ADC2, GD_PIN_FUNC_ANALOG_CH(1)}, /* ADC2_IN1 */
  {PORTA_2,					ADC0, GD_PIN_FUNC_ANALOG_CH(2)}, /* ADC0_IN2 */
  //{PORTA_2_ALT1,  ADC1, GD_PIN_FUNC_ANALOG_CH(2)}, /* ADC1_IN2 */
  //{PORTA_2_ALT2,  ADC2, GD_PIN_FUNC_ANALOG_CH(2)}, /* ADC2_IN2 */
  {PORTA_3,					ADC0, GD_PIN_FUNC_ANALOG_CH(3)}, /* ADC0_IN3 */
  //{PORTA_3_ALT1,  ADC1, GD_PIN_FUNC_ANALOG_CH(3)}, /* ADC1_IN3 */
  //{PORTA_3_ALT2,  ADC2, GD_PIN_FUNC_ANALOG_CH(3)}, /* ADC2_IN3 */
  {PORTA_4,					ADC0, GD_PIN_FUNC_ANALOG_CH(4)}, /* ADC0_IN4 */
  //{PORTA_4_ALT1,  ADC1, GD_PIN_FUNC_ANALOG_CH(4)}, /* ADC1_IN4 */
  {PORTA_5,					ADC0, GD_PIN_FUNC_ANALOG_CH(5)}, /* ADC0_IN5 */
  //{PORTA_5_ALT1,  ADC1, GD_PIN_FUNC_ANALOG_CH(5)}, /* ADC1_IN5 */
  {PORTA_6,					ADC0, GD_PIN_FUNC_ANALOG_CH(6)}, /* ADC0_IN6 */
  //{PORTA_6_ALT1,  ADC1, GD_PIN_FUNC_ANALOG_CH(6)}, /* ADC1_IN6 */
  {PORTA_7,					ADC0, GD_PIN_FUNC_ANALOG_CH(7)}, /* ADC0_IN7 */
  //{PORTA_7_ALT1,  ADC1, GD_PIN_FUNC_ANALOG_CH(7)}, /* ADC1_IN7 */
  {PORTB_0,					ADC0, GD_PIN_FUNC_ANALOG_CH(8)}, /* ADC0_IN8 */
  //{PORTB_0_ALT1,  ADC1, GD_PIN_FUNC_ANALOG_CH(8)}, /* ADC1_IN8 */
  {PORTB_1,					ADC0, GD_PIN_FUNC_ANALOG_CH(9)}, /* ADC0_IN9 */
  //{PORTB_1_ALT1,  ADC1, GD_PIN_FUNC_ANALOG_CH(9)}, /* ADC1_IN9 */
  {PORTC_0,					ADC0, GD_PIN_FUNC_ANALOG_CH(10)}, /* ADC0_IN10 */
  //{PORTC_0_ALT1,  ADC1, GD_PIN_FUNC_ANALOG_CH(10)}, /* ADC1_IN10 */
  //{PORTC_0_ALT2,  ADC2, GD_PIN_FUNC_ANALOG_CH(10)}, /* ADC2_IN10 */
  {PORTC_1,					ADC0, GD_PIN_FUNC_ANALOG_CH(11)}, /* ADC0_IN11 */
  //{PORTC_1_ALT1,  ADC1, GD_PIN_FUNC_ANALOG_CH(11)}, /* ADC1_IN11 */
  //{PORTC_1_ALT2,  ADC2, GD_PIN_FUNC_ANALOG_CH(11)}, /* ADC2_IN11 */
  {PORTC_2,					ADC0, GD_PIN_FUNC_ANALOG_CH(12)}, /* ADC0_IN12 */
  //{PORTC_2_ALT1,  ADC1, GD_PIN_FUNC_ANALOG_CH(12)}, /* ADC1_IN12 */
  //{PORTC_2_ALT2,  ADC2, GD_PIN_FUNC_ANALOG_CH(12)}, /* ADC2_IN12 */
  {PORTC_3,					ADC0, GD_PIN_FUNC_ANALOG_CH(13)}, /* ADC0_IN13 */
  //{PORTC_3_ALT1,  ADC1, GD_PIN_FUNC_ANALOG_CH(13)}, /* ADC1_IN13 */
  //{PORTC_3_ALT2,  ADC2, GD_PIN_FUNC_ANALOG_CH(13)}, /* ADC2_IN13 */
  {PORTC_4,					ADC0, GD_PIN_FUNC_ANALOG_CH(14)}, /* ADC0_IN14 */
  //{PORTC_4_ALT1,  ADC1, GD_PIN_FUNC_ANALOG_CH(14)}, /* ADC1_IN14 */
  {PORTC_5,					ADC0, GD_PIN_FUNC_ANALOG_CH(15)}, /* ADC0_IN15 */
  //{PORTC_5_ALT1,  ADC1, GD_PIN_FUNC_ANALOG_CH(15)}, /* ADC1_IN15 */
  //{ADC_TEMP,				ADC0, GD_PIN_FUNC_ANALOG_CH(16)}, /* ADC0_IN16 */
  //{ADC_VREF,				ADC0, GD_PIN_FUNC_ANALOG_CH(17)}, /* ADC0_IN17 */
  {NC,							NP,		0}
};

//#ifdef HAL_DAC_MODULE_ENABLED
/* DAC PinMap */
const PinMap PinMap_DAC[] = {
  {PORTA_4,	DAC0, GD_PIN_FUNC_ANALOG_CH(1)},	/* DAC_OUT0 */
  {PORTA_5,	DAC0, GD_PIN_FUNC_ANALOG_CH(2)},	/* DAC_OUT1 */
  {NC,			NP,		0}
};
//#endif

/* I2C PinMap */
const PinMap PinMap_I2C_SDA[] = {
  {PORTB_7,		I2C0, GD_PIN_DATA_REMAP(PIN_MODE_AF_OD, PIN_MODE_INPUT_FLOATING, DISABLE_I2C0_REMAP)},
  {PORTB_9,		I2C0, GD_PIN_DATA_REMAP(PIN_MODE_AF_OD, PIN_MODE_INPUT_FLOATING, I2C0_REMAP)},           /* GPIO_I2C0_REMAP */
  {PORTB_11,	I2C1, GD_PIN_DATA(PIN_MODE_AF_OD, PIN_MODE_INPUT_FLOATING, 0) },
  {NC,				NP,		0}
};

const PinMap PinMap_I2C_SCL[] = {
  {PORTB_6,		I2C0, GD_PIN_DATA_REMAP(PIN_MODE_AF_OD, PIN_MODE_INPUT_FLOATING, DISABLE_I2C0_REMAP)},
  {PORTB_8,		I2C0, GD_PIN_DATA_REMAP(PIN_MODE_AF_OD, PIN_MODE_INPUT_FLOATING, I2C0_REMAP)},           /* GPIO_I2C1_REMAP */
  {PORTB_10,	I2C1, GD_PIN_DATA(PIN_MODE_AF_OD, PIN_MODE_INPUT_FLOATING, 0)},
  {NC,				NP,		0}
};

/* PWM PinMap */
const PinMap PinMap_PWM[] = {
  {PORTA_0,       TIMER1, GD_PIN_DATA_EXT_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, REMAP_NONE, 0, 0)},                      	/* TIMER1_CH0 */
  //{PORTA_0_ALT1,  TIMER1, GD_PIN_DATA_EXT_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, TIMER1_PARTIAL_REMAP1, 0, 0)},           /* TIMER1_CH0 */
  //{PORTA_0_ALT2,  TIMER4, GD_PIN_DATA_EXT_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, REMAP_NONE, 0, 0)},                      /* TIMER4_CH0 */
  {PORTA_1,       TIMER1, GD_PIN_DATA_EXT_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, REMAP_NONE, 1, 0)},       									/* TIMER1_CH1 */
  //{PORTA_1_ALT1,  TIMER1, GD_PIN_DATA_EXT_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, TIMER1_PARTIAL_REMAP1, 1, 0)},           /* TIMER1_CH1 */
  //{PORTA_1_ALT2,  TIMER4, GD_PIN_DATA_EXT_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, REMAP_NONE, 1, 0)},                      /* TIMER4_CH1 */
  {PORTA_2,       TIMER1, GD_PIN_DATA_EXT_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, REMAP_NONE, 2, 0)},       									/* TIMER1_CH2 */
  //{PORTA_2_ALT1,  TIMER1, GD_PIN_DATA_EXT_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, TIMER1_PARTIAL_REMAP0, 2, 0)},           /* TIMER1_CH2 */
  //{PORTA_2_ALT2,  TIMER4, GD_PIN_DATA_EXT_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, REMAP_NONE, 2, 0)},                      /* TIMER4_CH2 */
  //{PORTA_3,       TIMER1, GD_PIN_DATA_EXT_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, DISABLE_TIMER1_FULL_REMAP, 3, 0)},       /* TIMER1_CH3 */
	//{PORTA_3_ALT1,  TIMER1, GD_PIN_DATA_EXT_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, TIMER1_PARTIAL_REMAP0, 3, 0)},           /* TIMER1_CH3 */
	{PORTA_3,       TIMER4, GD_PIN_DATA_EXT_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, REMAP_NONE, 3, 0)},                      	/* TIMER4_CH3 */
	{PORTA_6,       TIMER2, GD_PIN_DATA_EXT_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, REMAP_NONE, 0, 0)},       									/* TIMER2_CH0 */
	//{PORTA_7,       TIMER1, GD_PIN_DATA_EXT_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, TIMER0_PARTIAL_REMAP, 0, 1)},            /* TIMER0_CH0_ON */
	//{PORTA_7_ALT1,  TIMER2, GD_PIN_DATA_EXT_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, DISABLE_TIMER2_FULL_REMAP, 1, 0)},       /* TIMER2_CH1 */
	{PORTA_7,       TIMER7, GD_PIN_DATA_EXT_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, REMAP_NONE, 0, 1)},                      	/* TIMER7_CH0_ON */
	{PORTA_8,       TIMER0, GD_PIN_DATA_EXT_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, REMAP_NONE, 0, 0)},       									/* TIMER0_CH0 */
	//{PORTA_8_ALT1,  TIMER0, GD_PIN_DATA_EXT_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, TIMER0_PARTIAL_REMAP, 0, 0)},            /* TIMER0_CH0 */
	{PORTA_9,       TIMER0, GD_PIN_DATA_EXT_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, REMAP_NONE, 1, 0)},       									/* TIMER0_CH1 */
	//{PORTA_9_ALT1,  TIMER0, GD_PIN_DATA_EXT_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, TIMER0_PARTIAL_REMAP, 1, 0)},            /* TIMER0_CH1 */
	{PORTA_10,      TIMER0, GD_PIN_DATA_EXT_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, REMAP_NONE, 2, 0)},       									/* TIMER0_CH2 */
	//{PORTA_10_ALT1, TIMER0, GD_PIN_DATA_EXT_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, TIMER0_PARTIAL_REMAP, 2, 0)},            /* TIMER0_CH2 */
	{PORTA_11,      TIMER0, GD_PIN_DATA_EXT_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, REMAP_NONE, 3, 0)},       									/* TIMER0_CH3 */
	//{PORTA_11_ALT1, TIMER0, GD_PIN_DATA_EXT_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, TIMER0_PARTIAL_REMAP, 3, 0)},            /* TIMER0_CH3 */
	{PORTA_15,      TIMER1, GD_PIN_DATA_EXT_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, TIMER1_PARTIAL_REMAP0, 0, 0)},           	/* TIMER1_CH0 */
	//{PORTA_15_ALT1, TIMER1, GD_PIN_DATA_EXT_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, TIMER1_FULL_REMAP, 0, 0)},               /* TIMER1_CH0 */
	//{PORTB_0,       TIMER0, GD_PIN_DATA_EXT_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, TIMER0_PARTIAL_REMAP, 1, 1)},            /* TIMER0_CH1_ON */
	{PORTB_0,       TIMER2, GD_PIN_DATA_EXT_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, REMAP_NONE, 2, 0)},       									/* TIMER2_CH2 */
	//{PORTB_0_ALT2,  TIMER2, GD_PIN_DATA_EXT_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, TIMER2_PARTIAL_REMAP, 2, 0)},            /* TIMER2_CH2 */
	//{PORTB_0_ALT3,  TIMER7, GD_PIN_DATA_EXT_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, REMAP_NONE, 1, 1)},                      /* TIMER7_CH1_ON */
	{PORTB_1,       TIMER0, GD_PIN_DATA_EXT_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, TIMER0_PARTIAL_REMAP, 2, 1)},            	/* TIMER0_CH2_ON */
	//{PORTB_1_ALT1,  TIMER2, GD_PIN_DATA_EXT_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, DISABLE_TIMER2_FULL_REMAP, 3, 1)},       /* TIMER2_CH3 */
	//{PORTB_1_ALT2,  TIMER2, GD_PIN_DATA_EXT_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, TIMER2_PARTIAL_REMAP, 3, 0)},            /* TIMER2_CH3 */
	//{PORTB_1_ALT3,  TIMER7, GD_PIN_DATA_EXT_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, REMAP_NONE, 2, 1)},                      /* TIMER7_CH2_ON */
	{PORTB_3,       TIMER1, GD_PIN_DATA_EXT_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, TIMER1_PARTIAL_REMAP0, 1, 0)},           	/* TIMER1_CH1 */
	//{PORTB_3_ALT1,  TIMER1, GD_PIN_DATA_EXT_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, TIMER1_FULL_REMAP, 1, 0)},               /* TIMER1_CH1 */
	{PORTB_4,       TIMER2, GD_PIN_DATA_EXT_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, TIMER2_PARTIAL_REMAP, 0, 0)},            	/* TIMER2_CH0 */
	{PORTB_5,       TIMER2, GD_PIN_DATA_EXT_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, TIMER2_PARTIAL_REMAP, 1, 0)},            	/* TIMER2_CH1 */
	{PORTB_6,       TIMER3, GD_PIN_DATA_EXT_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, REMAP_NONE, 0, 0)},            						/* TIMER3_CH0 */
	{PORTB_7,       TIMER3, GD_PIN_DATA_EXT_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, REMAP_NONE, 1, 0)},            						/* TIMER3_CH1 */
	{PORTB_8,       TIMER3, GD_PIN_DATA_EXT_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, REMAP_NONE, 2, 0)},            						/* TIMER3_CH2 */
	{PORTB_9,       TIMER3, GD_PIN_DATA_EXT_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, REMAP_NONE, 3, 0)},            						/* TIMER3_CH3 */
	{PORTB_10,      TIMER1, GD_PIN_DATA_EXT_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, TIMER1_PARTIAL_REMAP1, 2, 0)},           	/* TIMER1_CH2 */
	//{PORTB_10_ALT1, TIMER1, GD_PIN_DATA_EXT_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, TIMER1_FULL_REMAP, 2, 0)},               /* TIMER1_CH2 */
	{PORTB_11,      TIMER1, GD_PIN_DATA_EXT_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, TIMER1_PARTIAL_REMAP1, 3, 0)},           	/* TIMER1_CH3 */
	//{PORTB_11_ALT1, TIMER1, GD_PIN_DATA_EXT_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, TIMER1_FULL_REMAP, 3, 0)},               /* TIMER1_CH3 */
	{PORTB_13,      TIMER0, GD_PIN_DATA_EXT_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, REMAP_NONE, 0, 1)},       									/* TIMER0_CH0_ON */
	{PORTB_14,      TIMER0, GD_PIN_DATA_EXT_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, REMAP_NONE, 1, 1)},       									/* TIMER0_CH1_ON */
	{PORTB_15,      TIMER0, GD_PIN_DATA_EXT_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, REMAP_NONE, 2, 1)},       									/* TIMER0_CH2_ON */
	{PORTC_6,       TIMER2, GD_PIN_DATA_EXT_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, TIMER2_FULL_REMAP, 0, 0)},               	/* TIMER2_CH0 */
	//{PORTC_6_ALT,   TIMER7, GD_PIN_DATA_EXT_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, REMAP_NONE, 0, 0)},                      /* TIMER7_CH0 */
	{PORTC_7,       TIMER2, GD_PIN_DATA_EXT_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, TIMER2_FULL_REMAP, 1, 0)},               	/* TIMER2_CH1 */
	//{PORTC_7_ALT,   TIMER7, GD_PIN_DATA_EXT_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, REMAP_NONE, 1, 0)},                      /* TIMER7_CH1 */
	//{PORTC_8,       TIMER2, GD_PIN_DATA_EXT_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, TIMER2_FULL_REMAP, 2, 0)},               /* TIMER2_CH2 */
	{PORTC_8,       TIMER7, GD_PIN_DATA_EXT_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, REMAP_NONE, 2, 0)},                      /* TIMER7_CH2 */
	{PORTC_9,       TIMER2, GD_PIN_DATA_EXT_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, TIMER2_FULL_REMAP, 3, 0)},               /* TIMER2_CH3 */
	//{PORTC_9_ALT,   TIMER7, GD_PIN_DATA_EXT_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, REMAP_NONE, 3, 0)},                      /* TIMER7_CH3 */
	{NC,    NP,    0}
};

/* USART PinMap */
const PinMap PinMap_UART_TX[] = {
	{PORTA_2,       USART1, GD_PIN_DATA_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, REMAP_NONE)},        					/* USART1_TX */
	{PORTA_9,       USART0, GD_PIN_DATA_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, REMAP_NONE)},        					/* USART0_TX */
	{PORTB_6,       USART0, GD_PIN_DATA_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, USART0_REMAP)},                /* USART0_TX */
	{PORTB_10,      USART2, GD_PIN_DATA_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, REMAP_NONE)},                  /* USART2_TX */
	{PORTC_10,      UART3, GD_PIN_DATA_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, REMAP_NONE)},                   /* UART3_TX */
	//{PORTC_10_ALT,  USART2, GD_PIN_DATA_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, USART2_PARTIAL_REMAP)},      /* USART2_TX */
	{PORTC_12,      UART4, GD_PIN_DATA_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, REMAP_NONE)},                   /* UART4_TX */
	{NC,    NP,     0}
};

const PinMap PinMap_UART_RX[] = {
	{PORTA_3,       USART1, GD_PIN_DATA_REMAP(PIN_MODE_INPUT, PIN_MODE_INPUT_PU, REMAP_NONE)},        					/* USART1_RX */
	{PORTA_10,      USART0, GD_PIN_DATA_REMAP(PIN_MODE_INPUT, PIN_MODE_INPUT_PU, REMAP_NONE)},        					/* USART0_RX */
	{PORTB_7,       USART0, GD_PIN_DATA_REMAP(PIN_MODE_INPUT, PIN_MODE_INPUT_PU, USART0_REMAP)},                /* USART0_RX */
	{PORTB_11,      USART2, GD_PIN_DATA_REMAP(PIN_MODE_INPUT, PIN_MODE_INPUT_PU, REMAP_NONE)},                  /* USART2_RX */
	{PORTC_11,      UART3, GD_PIN_DATA_REMAP(PIN_MODE_INPUT, PIN_MODE_INPUT_PU, REMAP_NONE)},                   /* UART3_RX */
	//{PORTC_11_ALT,  USART2, GD_PIN_DATA_REMAP(PIN_MODE_INPUT, PIN_MODE_INPUT_PU, USART2_PARTIAL_REMAP)},      /* USART2_RX */
	{PORTD_2,       UART4, GD_PIN_DATA_REMAP(PIN_MODE_INPUT, PIN_MODE_INPUT_PU, REMAP_NONE)},                   /* UART4_RX */
	{NC,    NP,     0}
};

const PinMap PinMap_UART_RTS[] = {
	{PORTA_1,       USART1, GD_PIN_DATA_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, REMAP_NONE)},        					/* USART1_RTS */
	{PORTA_12,      USART0, GD_PIN_DATA_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, REMAP_NONE)},                  /* USART0_RTS */
	{PORTB_14,      USART2, GD_PIN_DATA_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, REMAP_NONE)},                  /* USART2_RTS */
	{PORTB_14,      USART2, GD_PIN_DATA_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, USART2_PARTIAL_REMAP)},        /* USART2_RTS */
	{NC,    NP,    0}
};

const PinMap PinMap_UART_CTS[] = {
	{PORTA_0,       USART1, GD_PIN_DATA_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, REMAP_NONE)},                  /* USART1_CTS */
	{PORTA_11,      USART0, GD_PIN_DATA_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, REMAP_NONE)},                  /* USART0_CTS */
	{PORTB_13,      USART2, GD_PIN_DATA_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, REMAP_NONE)},   								/* USART2_CTS */
	{PORTB_13,      USART2, GD_PIN_DATA_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, USART2_PARTIAL_REMAP)},        /* USART2_CTS */
	{NC,    NP,    0}
};

/* SPI PinMap */
const PinMap PinMap_SPI_MOSI[] = {
	{PORTA_7,       SPI0, GD_PIN_DATA_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, REMAP_NONE)},            				/* SPI0_MOSI */
	//{PORTB_5,       SPI0, GD_PIN_DATA_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, SPI0_REMAP)},                  /* SPI0_MOSI */
	{PORTB_5,       SPI2, GD_PIN_DATA_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, REMAP_NONE)},                    /* SPI2_MOSI */
	{PORTB_15,      SPI1, GD_PIN_DATA_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, REMAP_NONE)},                    /* SPI1_MOSI */
	{NC,    NP,    0}
};

const PinMap PinMap_SPI_MISO[] = {
	{PORTA_6,       SPI0, GD_PIN_DATA_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, REMAP_NONE)},            				/* SPI0_MISO */
	//{PORTB_4,       SPI0, GD_PIN_DATA_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, SPI0_REMAP)},                  /* SPI0_MISO */
	{PORTB_4,       SPI2, GD_PIN_DATA_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, REMAP_NONE)},                    /* SPI2_MISO */
	{PORTB_14,      SPI1, GD_PIN_DATA_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, REMAP_NONE)},                    /* SPI1_MISO */
	{NC,    NP,    0}
};

const PinMap PinMap_SPI_SCLK[] = {
	{PORTA_5,       SPI0, GD_PIN_DATA_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, REMAP_NONE)},            				/* SPI0_SCLK */
	//{PORTB_3,       SPI0, GD_PIN_DATA_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, SPI0_REMAP)},                  /* SPI0_SCLK */
	{PORTB_3,       SPI2, GD_PIN_DATA_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, REMAP_NONE)},                    /* SPI2_SCLK */
	{PORTB_13,      SPI1, GD_PIN_DATA_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, REMAP_NONE)},                    /* SPI1_SCLK */
	{NC,    NP,    0}
};

const PinMap PinMap_SPI_SSEL[] = {
	{PORTA_4,       SPI0, GD_PIN_DATA_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, REMAP_NONE)},            				/* SPI0_SSEL */
	//{PORTA_15,      SPI0, GD_PIN_DATA_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, SPI0_REMAP)},                  /* SPI0_SSEL */
	{PORTA_15,      SPI2, GD_PIN_DATA_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, REMAP_NONE)},                    /* SPI2_SSEL */
	{PORTB_12,      SPI1, GD_PIN_DATA_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, REMAP_NONE)},                    /* SPI1_SSEL */
	{NC,    NP,    0}
};

/* CAN PinMap */
const PinMap PinMap_CAN_RD[] = {
	{PORTA_11, CAN0, GD_PIN_DATA_REMAP(PIN_MODE_INPUT, PIN_MODE_INPUT_FLOATING, REMAP_NONE)},                   /* CAN_RD */
	{PORTB_8,  CAN0, GD_PIN_DATA_REMAP(PIN_MODE_INPUT, PIN_MODE_INPUT_FLOATING, CAN_FULL_REMAP)},               /* CAN_RD */
	{NC,    NP,    0}
};

const PinMap PinMap_CAN_TD[] = {
	{PORTA_12, CAN0, GD_PIN_DATA_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_FLOATING, REMAP_NONE)},                   /* CAN0_TD */
	{PORTB_9,  CAN0, GD_PIN_DATA_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_FLOATING, CAN_FULL_REMAP)},               /* CAN0_TD */
	{NC,    NP,    0}
};

//const PinMap PinMap_USB[] = {
//  {PORTA_11, USB, GD_PIN_DATA_REMAP(PIN_MODE_INPUT, PIN_MODE_INPUT_FLOATING, REMAP_NONE)}, 										/* USB_DM */
//  {PORTA_12, USB, GD_PIN_DATA_REMAP(PIN_MODE_INPUT, PIN_MODE_INPUT_FLOATING, REMAP_NONE)}, 										/* USB_DP */
//  {NC,    NP,    0}
//};

const PinMap PinMap_SD[] = {
  {PORTB_8,  SDIO, GD_PIN_DATA_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, REMAP_NONE)},													/* SDIO_D4 */
  {PORTB_9,  SDIO, GD_PIN_DATA_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, REMAP_NONE)},                         /* SDIO_D5 */
  {PORTC_6,  SDIO, GD_PIN_DATA_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, REMAP_NONE)},                         /* SDIO_D6 */
  {PORTC_7,  SDIO, GD_PIN_DATA_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, REMAP_NONE)},                         /* SDIO_D7 */
  {PORTC_8,  SDIO, GD_PIN_DATA_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, REMAP_NONE)},                         /* SDIO_D0 */
  {PORTC_9,  SDIO, GD_PIN_DATA_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, REMAP_NONE)},                         /* SDIO_D1 */
  {PORTC_10, SDIO, GD_PIN_DATA_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, REMAP_NONE)},                         /* SDIO_D2 */
  {PORTC_11, SDIO, GD_PIN_DATA_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_PU, REMAP_NONE)},                         /* SDIO_D3 */
  {PORTC_12, SDIO, GD_PIN_DATA_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_FLOATING, REMAP_NONE)},                   /* SDIO_CK */
  {PORTD_2,  SDIO, GD_PIN_DATA_REMAP(PIN_MODE_AF_PP, PIN_MODE_INPUT_FLOATING, REMAP_NONE)},                   /* SDIO_CMD */
  {NC,    NP,    0}
};
